### ISSUE TITLE
Incorporate comments by reviewer in paper

### ISSUE THREAD

**Issue by JeanWi** [UU-ER/AdOpT-NET0#316]
- Line 21-22: You state that mulit-energy systems "are highly complex but also offer synergies to reduce costs and environmental impact." This reads like a definitive statement that deserves a reference. (Not that I disagree with the statement at all! Just a single reference here would be good to defend the need for multi-energy modelling).

- Table 1: Thanks for the comprehensive table! Can you please be more specific with the pareto front methods implemented. Similar to how you have given stochastic scenarios through "Monte Carlo" sampling, listing methods of pareto fronts would be good (ie. MGA, ɛ-constraint, ect.. following definitions from the Hoffmann paper)

- Line 30-31: (Apologies in advance for this rather pedantic wording comment!) You note that AdOpT-NET0 "allows for a highly realistic assessment of individual technologies and their integration into an energy system". I have trouble with this wording when no evidence is provided (ie. a ref to a research paper / study) to show that improved technology representation correlates to more realistic technology investment/integration decisions. AdOpT-NET0 can describe technology specific operational constraints well (and closer represents reality), but this does not guarantee highly realistic integration answers over multiple time horizons. Can you please clarify how AdOpT-NET0's detailed technology representation translates into realistic assessments of energy integration questions. Or can you please soften the wording to align with a prescriptive analytics tool (ie. guide decision making) rather than a predictive analytics tool (ie. predicting what will happen in the future). To clarify, I have no issue with the statement of representing technologies more realistically (which you give references for later), but rather how this translates to more realistic future energy integration questions (which is likely difficult to measure?).

- Figure 1: The figure is clear, I just have a question about the reference. I see it says adapted from Tiggeloven et al.; and it seems to be a cropped version of Figure 2 from that paper (specifically, box 2d)? I am unsure if this requires the license of the figure to also be included with caption? @JeanWi, if this figure is cropped from the Tiggeloven et al. reference, maybe @AdamRJensen can confirm if stating "adaptation" alone is okay, or if the figure license is also required?

- Line 32-33: (A manuscript suggestion that you are free to take or leave) You note that "several complexity reduction algorithms can be adopted to deal with infeasible computation times". I believe this is a super valuable point, and explicitly listing them for the reader is useful. ie. Something along the lines of "Complexity reduction algorithms for modelling seasonal storage (Gabrielli et al., 2018) and high VRE systems (Weimann & Gazzani, 2022) are implemented." Having these algorithms already integrated is a big plus of AdOpT-NET0 and would be good to highlight!

- Line 36: Its great that the closed MATLAB version has been ported to Python and made openly available. Is there any relevant publications or similar that use or describe the MATLAB version that require a referencing here? Or has it been used solely for in-house business applications?

- Statement of need paragraph: Listing the specific technologies you represent in greater detail compared to existing models is great, as it helps the reader understand the novelty of this framework! Where further clarification will help is with the target user. In the opening sentence you break down the field into complex NLP frameworks, and simplified LP frameworks. The users of this different frameworks may be different, though? (ie. policy focused research questions will use LP frameworks, while power flow research question (as you mention) may want the NLP detail). It is a little unclear to me if AdOpT-NET0 can be used both as a policy support tool and a power flow analysis tool, or just one or the other (or a category I am missing!).

- Has AdOpT-NET0 been used in any publications (other than the forthcoming one by Wiegner et al.)? If so, please list them, else please just disregard this comment.

**Comment by julia1071** [comment]
**Tackled:**

Line 21-22: You state that mulit-energy systems "are highly complex but also offer synergies to reduce costs and environmental impact." This reads like a definitive statement that deserves a reference. (Not that I disagree with the statement at all! Just a single reference here would be good to defend the need for multi-energy modelling).

Table 1: Thanks for the comprehensive table! Can you please be more specific with the pareto front methods implemented. Similar to how you have given stochastic scenarios through "Monte Carlo" sampling, listing methods of pareto fronts would be good (ie. MGA, ɛ-constraint, ect.. following definitions from the Hoffmann paper)

Line 30-31: (Apologies in advance for this rather pedantic wording comment!) You note that AdOpT-NET0 "allows for a highly realistic assessment of individual technologies and their integration into an energy system". I have trouble with this wording when no evidence is provided (ie. a ref to a research paper / study) to show that improved technology representation correlates to more realistic technology investment/integration decisions. AdOpT-NET0 can describe technology specific operational constraints well (and closer represents reality), but this does not guarantee highly realistic integration answers over multiple time horizons. Can you please clarify how AdOpT-NET0's detailed technology representation translates into realistic assessments of energy integration questions. Or can you please soften the wording to align with a prescriptive analytics tool (ie. guide decision making) rather than a predictive analytics tool (ie. predicting what will happen in the future). To clarify, I have no issue with the statement of representing technologies more realistically (which you give references for later), but rather how this translates to more realistic future energy integration questions (which is likely difficult to measure?).

Figure 1: The figure is clear, I just have a question about the reference. I see it says adapted from Tiggeloven et al.; and it seems to be a cropped version of Figure 2 from that paper (specifically, box 2d)? I am unsure if this requires the license of the figure to also be included with caption? @JeanWi, if this figure is cropped from the Tiggeloven et al. reference, maybe @AdamRJensen can confirm if stating "adaptation" alone is okay, or if the figure license is also required?

Line 32-33: (A manuscript suggestion that you are free to take or leave) You note that "several complexity reduction algorithms can be adopted to deal with infeasible computation times". I believe this is a super valuable point, and explicitly listing them for the reader is useful. ie. Something along the lines of "Complexity reduction algorithms for modelling seasonal storage (Gabrielli et al., 2018) and high VRE systems (Weimann & Gazzani, 2022) are implemented." Having these algorithms already integrated is a big plus of AdOpT-NET0 and would be good to highlight!

Has AdOpT-NET0 been used in any publications (other than the forthcoming one by Wiegner et al.)? If so, please list them, else please just disregard this comment.

**Comment by julia1071** [comment]
**Questions:**

Line 36: Its great that the closed MATLAB version has been ported to Python and made openly available. Is there any relevant publications or similar that use or describe the MATLAB version that require a referencing here? Or has it been used solely for in-house business applications?

_I guess nothing relevant, since everything is copied over to python. Or should we ref to Lukas' work?_

Statement of need paragraph: Listing the specific technologies you represent in greater detail compared to existing models is great, as it helps the reader understand the novelty of this framework! Where further clarification will help is with the target user. In the opening sentence you break down the field into complex NLP frameworks, and simplified LP frameworks. The users of this different frameworks may be different, though? (ie. policy focused research questions will use LP frameworks, while power flow research question (as you mention) may want the NLP detail). It is a little unclear to me if AdOpT-NET0 can be used both as a policy support tool and a power flow analysis tool, or just one or the other (or a category I am missing!).

_We already mention that it bridges the gap between, i am a bit hesitant to mention specific applications, what do you think?_

**Comment by julia1071** [comment]
> **Tackled:**
> 
> Line 21-22: You state that mulit-energy systems "are highly complex but also offer synergies to reduce costs and environmental impact." This reads like a definitive statement that deserves a reference. (Not that I disagree with the statement at all! Just a single reference here would be good to defend the need for multi-energy modelling).
> 
> Table 1: Thanks for the comprehensive table! Can you please be more specific with the pareto front methods implemented. Similar to how you have given stochastic scenarios through "Monte Carlo" sampling, listing methods of pareto fronts would be good (ie. MGA, ɛ-constraint, ect.. following definitions from the Hoffmann paper)
> 
> Line 30-31: (Apologies in advance for this rather pedantic wording comment!) You note that AdOpT-NET0 "allows for a highly realistic assessment of individual technologies and their integration into an energy system". I have trouble with this wording when no evidence is provided (ie. a ref to a research paper / study) to show that improved technology representation correlates to more realistic technology investment/integration decisions. AdOpT-NET0 can describe technology specific operational constraints well (and closer represents reality), but this does not guarantee highly realistic integration answers over multiple time horizons. Can you please clarify how AdOpT-NET0's detailed technology representation translates into realistic assessments of energy integration questions. Or can you please soften the wording to align with a prescriptive analytics tool (ie. guide decision making) rather than a predictive analytics tool (ie. predicting what will happen in the future). To clarify, I have no issue with the statement of representing technologies more realistically (which you give references for later), but rather how this translates to more realistic future energy integration questions (which is likely difficult to measure?).
> 
> Figure 1: The figure is clear, I just have a question about the reference. I see it says adapted from Tiggeloven et al.; and it seems to be a cropped version of Figure 2 from that paper (specifically, box 2d)? I am unsure if this requires the license of the figure to also be included with caption? @JeanWi, if this figure is cropped from the Tiggeloven et al. reference, maybe @AdamRJensen can confirm if stating "adaptation" alone is okay, or if the figure license is also required?
> 
> Line 32-33: (A manuscript suggestion that you are free to take or leave) You note that "several complexity reduction algorithms can be adopted to deal with infeasible computation times". I believe this is a super valuable point, and explicitly listing them for the reader is useful. ie. Something along the lines of "Complexity reduction algorithms for modelling seasonal storage (Gabrielli et al., 2018) and high VRE systems (Weimann & Gazzani, 2022) are implemented." Having these algorithms already integrated is a big plus of AdOpT-NET0 and would be good to highlight!
> 
> Has AdOpT-NET0 been used in any publications (other than the forthcoming one by Wiegner et al.)? If so, please list them, else please just disregard this comment.

@JeanWi _ Ive added mine, can you add a few words on your forthcoming paper as well?_
